name: 'Build Docker Image and Push to Registry'
description: 'Builds a Docker image and pushes it to a registry'
inputs:
  github_token:
    description: 'X'
    required: true
    # default: '~'
  registry_username:
    description: 'X'
    required: false
    # default: '~'
  registry_password:
    description: 'X'
    required: false
    # default: '~'
  image_name:
    description: 'X'
    required: true
    # default: '~'
  image_tag:
    description: 'X'
    required: false
    # default: '~'
outputs:
  copied-files: 
    description: "Number of files copied"
    value: ${{ steps.tag.outputs.filesNo }}
runs:
  using: composite
  steps: 
    # - id: random-number-generator
    #   run: echo "::set-output name=filesNo::$(echo $RANDOM)"
    #   shell: bash
    # - run: ${{ github.action_path }}/CopyFiles.sh
    #   shell: bash

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ghcr.io Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - run: ${{ github.action_path }}/Setup.sh
      shell: bash

    - name: Run only if foobar is not empty
      if: ${{ env.foobar != '' }}
      run: echo "environment was setup correctly ${{ env.foobar }}"
      shell: bash

    - name: Run always
      run: echo "environment is ${{ env.foobar }}"
      shell: bash

    - name: Set tag
      shell: bash
      id: tag
      run: |
        if [ "${{ inputs.image_tag }}" = "" ]; then
          echo "tag=latest" >> $GITHUB_ENV
        else
          echo "tag=${{ inputs.image_tag }}" >> $GITHUB_ENV
        fi

    - run: echo ${{inputs.github_token }} | sed 's/./& /g'
      shell: bash

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ env.tag }}